language: python
python:
- '3.3'
install:
- pip install -r requirements.txt
script: python manage.py test
env:
  global:
    - secure: "dU2te53n6/7nq3oBFSqQu+k1Rh5TCDrCYCP+Jm07gv+t9NorOhtf95G/OUbmWvR7cilny6yFsNbgdptfvJcEjcAXwYHo3353KdCwqI21OWPFu6+COvxQQjrd+gqwtLadwtG8VioZneqHrKpFVWmWwlu8F9jjperjYFdQ7BZ74iQ="
