language: python

python:
  - '3.3'

env:
  global:
    - secure: "fX9l/W4jJ/l/VuWhzUi6Q15xBH7EWjJ+RhqQoBcopSYr/To8OI/lVBJv0SL95D6dbzw4uT/vlkDs9+EnH5mZpXnn9ZjkdYruT/cQhob2g6uQZY7cIIU+Id7w7UyTfXxPOZQ4e5olWQMD7CSpDSvtX7Fzk3tB8zdpRnXcz+ZeMZc="

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install -r requirements.txt

# TODO: Selenium functional tests
script: python manage.py test lists

