#!/bin/bash

PROJECT_DIR=YOUR_PROJECT_DIR
SERVER_ADDR=YOUR_SERVER_ADDR

WSGI_APP=superlists.wsgi:application
SERVER_PID=$PROJECT_DIR/gunicorn.pid
SOURCE_DIR=$PROJECT_DIR/source
GUNICORN=$PROJECT_DIR/virtualenv/bin/gunicorn

start_server () {
    if [ -f $1 ]; then
        echo "PID exists for server $2"
    else
        cd $SOURCE_DIR
        echo "Starting server $2"
        $GUNICORN --daemon --bind=$2 --pid=$1 $WSGI_APP
    fi
}

stop_server (){
    if [ -f $1 ]; then
        echo "Stopping server $2"
        kill `cat $1`
    else
        echo "No PID for server $2"
    fi
}

case "$1" in
'start')
  start_server $SERVER_PID $SERVER_ADDR
  ;;
'stop')
  stop_server $SERVER_PID $SERVER_ADDR
  ;;
'restart')
  stop_server $SERVER_PID $SERVER_ADDR
  sleep 2
  start_server $SERVER_PID $SERVER_ADDR
  ;;
*)
  echo "Usage: $0 { start | stop | restart }"
  ;;
esac

exit 0

